### provision AWS EC2 instance
- hosts: localhost
  connection: local
  gather_facts: false
  user: root
  pre_tasks:
    - include_vars: variables.yml
  tasks:
    - name: "Provision AWS Instance"
      local_action: ec2
                    aws_access_key:"{{ ec2_access_id }}"
                    aws_secret_key:"{{ ec2_access_key }}"
                    group:"{{ ec2_grp }}"
                    instance_type:"{{ insta_type }}"
                    image:"{{ ami_id }}"
                    wait:true
                    region:"{{ ec2_region }}"
                    keypair:"{{ key_pair }}"
                    count=1
      register: ec2

    - debug:
        var: item.public_ip
      with_items: "{{ ec2_instances }}"
    - name: "Adding Host"
      add_host:
       hostname: Webserver
       ansible_host: "{{ ec2.instances.0.public_ip }}"
       ansible_port: 22
       ansible_user: "ubuntu"
       ansible_ssh_private_key_file: "/root/key_techie.pem"
       ansible_ssh_common_args: "-o StrctHostKeyChecking=no"
   
    - name: "Initialize the instances"
      wait_for:
        port: 22
        host: "{{ ec2.instances.0.public_ip }}"
        timeout: 80
        state: started
        delay: 10
        
